### ISSUE TITLE
Teams not being assigned as Owners on a Task

### ISSUE THREAD

**Issue by JohnBarton27** [MediaYouCanFeel/Azzenda#166]
Post:
![azzenda teams task owners post](https://cloud.githubusercontent.com/assets/4752520/11102543/1bb8550e-888b-11e5-86e4-063d98e9b361.JPG)

JSON resposne:
![azzenda teams task owners json](https://cloud.githubusercontent.com/assets/4752520/11102559/367b75e2-888b-11e5-9a56-955982945414.JPG)

**Comment by krispycheez** [comment]
This appears to be fixed
